FEATURE: Caches schema
Sebobo/Shel.Neos.Schema pull request #13
Opened 2021-09-14 13:52 UTC by PRGfx

Creates a new schema for cache frontends, backends and their options based on https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Caching.html

2021-09-14 14:01 UTC, Sebobo requested changes
Awesome thx! Noticed only one issue at first glance.
Have to test it manually.

2021-09-14 15:57 UTC, PRGfx commented on Caches.Schema.json
> +        "defaultLifeTime": {
oh, you are of course right

2021-09-21 07:00 UTC, Sebobo approved these changes

2021-09-21 07:00 UTC, Sebobo approved these changes

2021-09-21 07:00 UTC, merged